#!/bin/bash
set -eu

DOTPATH="${HOME}/dotfiles"

. ${DOTPATH}/etc/logger.sh

cd ${DOTPATH}

# 必要なコマンドがインストールされているかチェックする
function check_command() {
  if !(type "wget" > /dev/null 2>&1); then
    log -l error "wget command is not exist"
    exit 1
  else
    log "all necessary commands are already installd!"
  fi
}

# カラースキームのデータをダウンロードする
function download_vim_color() {
  # hybridのカラースキームをダウンロードする
  if [ ! -f ${DOTPATH}/.vim/colors/hybrid.vim ]; then
    wget https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -P ${DOTPATH}/.vim/colors/
  fi
}

# Neovim用のカラースキームデータをダウンロードする
function download_nvim_color() {
  # Neovim用カラースキームの保存先
  local NVIM_COLOR_DIR="${HOME}/.config/nvim/colors"

  log "install color scheme for Neovim"

  if [ ! -f ${NVIM_COLOR_DIR}/hybrid.vim ]; then
    wget https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -P ${NVIM_COLOR_DIR}/
  else
    log "hybrid.vim is already installed."
  fi
}

# Neovimのプラグインマネージャーをインストールする
function download_packer_nvim() {
  local PACKER_DIR="${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"

  log "install packer.nvim"

  if [ ! -d ${PACKER_DIR} ]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim ${PACKER_DIR}
  else
    log "packer.nvim is already installed."
  fi
}

# zshのプラグインマネージャーをインストールする
function download_zsh_plugin_manager() {
  local ZPLUG_DIR="${HOME}/.zplug"

  if [ ! -d ${ZPLUG_DIR} ]; then
    log "install zplug"
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  else
    log "zplug is already installed."
  fi
}

# プロンプトにgitの情報を出力するためのスクリプトをダウンロード
function download_git_prompt() {
  local GIT_PROMPT_FILE="${HOME}/.git-prompt.sh"

  if [ ! -f ${GIT_PROMPT_FILE} ]; then
    log "install git-prompt"
    curl -sL https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ${HOME}/.git-prompt.sh
  else
    log "git-prompt is already installed."
  fi
}

function fzf_install() {
  # fzfコマンドのインストール
  if !(type fzf > /dev/null 2>&1); then
    log "install fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git ${HOME}/.fzf
    ${HOME}/.fzf/install
  fi
}

# main関数
# インストールなどの初期設定のみを行う
function main () {
  # コマンドの存在チェク
  check_command

  # zshのプラグインマネージャーをインストールする
  download_zsh_plugin_manager

  # git-promptをインストールする
  download_git_prompt

  # vimのカラースキームをダウンロード
  # download_vim_color

  # Neovimのカラースキームをインストール
  download_nvim_color

  # Neovimのプラグインマネージャーをインストール
  download_packer_nvim

  # fzfのインストール
  fzf_install
}

main

exit 0
