#!/bin/bash
set -eu

DOTPATH="${HOME}/dotfiles"

cd ${DOTPATH}

# カラースキームのデータをダウンロードする
function download_vim_color() {
  # hybridのカラースキームをダウンロードする
  if [ ! -f ${DOTPATH}/.vim/colors/hybrid.vim ]; then
    wget https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -P ${DOTPATH}/.vim/colors/
  fi
}

function fzf_install() {
  # fzfコマンドのインストール
  if !(type fzf > /dev/null 2>&1); then
    echo 'install fzf...'
    # Macの場合はhomebrewを使ってインストールする
    case "$(uname)" in
      'Darwin')
        brew install fzf
        ;;
      *)
        git clone --depth 1 https://github.com/junegunn/fzf.git ${DOTPATH}/downloads/.fzf
        ${DOTPATH}/downloads/.fzf/install
        ;;
    esac
  fi
}

# main関数
# インストールなどの初期設定のみを行う
function main () {
  # vimのカラースキームをダウンロード
  # download_vim_color

  # fzfのインストール
  fzf_install
}

main

exit 0
