#!/bin/bash
set -eu

DOTPATH="${HOME}/dotfiles"

. ${DOTPATH}/etc/logger.sh

cd ${DOTPATH}

# 必要なコマンドがインストールされているかチェックする
function check_command() {
  if !(type "wget" > /dev/null 2>&1); then
    log -l error "wget command is not exist"
    exit 1
  else
    log "all necessary commands are already installd!"
  fi
}

# カラースキームのデータをダウンロードする
function download_vim_color() {
  # hybridのカラースキームをダウンロードする
  if [ ! -f ${DOTPATH}/.vim/colors/hybrid.vim ]; then
    wget https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -P ${DOTPATH}/.vim/colors/
  fi
}

# Neovim用のカラースキームデータをダウンロードする
function download_nvim_color() {
  # Neovim用カラースキームの保存先
  local NVIM_COLOR_DIR="${HOME}/.config/nvim/colors"

  log "install color scheme for Neovim"

  if [ ! -f ${NVIM_COLOR_DIR}/hybrid.vim ]; then
    wget https://raw.githubusercontent.com/w0ng/vim-hybrid/master/colors/hybrid.vim -P ${NVIM_COLOR_DIR}/
  else
    log "hybrid.vim is already installed."
  fi
}

# Neovimのプラグインマネージャーをインストールする
function download_packer_nvim() {
  local PACKER_DIR="${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim"

  log "install packer.nvim"

  if [ ! -d ${PACKER_DIR} ]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim ${PACKER_DIR}
  else
    log "packer.nvim is already installed."
  fi
}

function fzf_install() {
  # fzfコマンドのインストール
  if !(type fzf > /dev/null 2>&1); then
    log "install fzf..."
    # Macの場合はhomebrewを使ってインストールする
    case "$(uname)" in
      'Darwin')
        brew install fzf
        ;;
      *)
        git clone --depth 1 https://github.com/junegunn/fzf.git ${DOTPATH}/downloads/.fzf
        ${DOTPATH}/downloads/.fzf/install
        ;;
    esac
  fi
}

# main関数
# インストールなどの初期設定のみを行う
function main () {
  # コマンドの存在チェク
  check_command

  # vimのカラースキームをダウンロード
  # download_vim_color

  # Neovimのカラースキームをインストール
  download_nvim_color

  # Neovimのプラグインマネージャーをインストール
  download_packer_nvim

  # fzfのインストール
  fzf_install
}

main

exit 0
