#!/bin/bash
set -eu

DOTPATH="${HOME}/dotfiles"

. ${DOTPATH}/etc/logger.sh
. ${DOTPATH}/etc/neovim_setting.sh

cd ${DOTPATH}

# main関数
# 全ての設定ファイルに対してシンボリックリンクを作成する
function main () {

  local DOTLIST=(".vimrc" ".bash_profile" ".zprofile" ".zshrc")
  DOTLIST+=(".bashrc")
  DOTLIST+=(".tmux.conf")
  DOTLIST+=(".Brewfile")

  for var in ${DOTLIST[@]}
  do
    create_ln ${var}
  done

  # Neovim -----------------------------------
  neovim_setting

  # Claude Skills ----------------------------
  claude_skills_setting
}

# シンボリックリンクを貼る関数
# 同じファイルが存在する場合、上書きする
# $1: 対象ファイル
function create_ln () {
  local FILE=$1

  ln -vsf ${DOTPATH}/${FILE} ${HOME}/${FILE}
  return 0
}

# ホームディレクトリ直下に対象のディレクトリがない場合は作成する関数
# $1: 対象ディレクトリ
function set_dir () {
  local DIR=$1

  if [[ ! -d ${HOME}/${DIR} ]]; then
    mkdir -p ${HOME}/${DIR}
  fi
  return 0
}

# Claude Skillsのシンボリックリンクを設定する関数
function claude_skills_setting () {
  # ホームディレクトリ直下に.claude/skillsディレクトリが存在しない場合は作成
  set_dir ".claude/skills"

  SKILLS_DIR=("${DOTPATH}/.claude/skills/*")

  for skill_dir in ${SKILLS_DIR[@]}
  do
    rel_path="${skill_dir#${DOTPATH}/}"   # 先頭の ${DOTPATH}/ を取り除く
    if [[ ! -L ${HOME}/${rel_path} ]]; then
      # シンボリックリンクが存在しないときのみ作成
      echo "${DOTPATH}/${rel_path} ${HOME}/${rel_path}"
      create_ln ${rel_path}
    fi
  done
}

# main関数実行
main


exit 0
