#!/bin/bash
set -eu

DOTPATH="${HOME}/dotfiles"

. ${DOTPATH}/etc/logger.sh
. ${DOTPATH}/etc/fish_setting.sh
. ${DOTPATH}/etc/neovim_setting.sh

cd ${DOTPATH}

# main関数
# 全ての設定ファイルに対してシンボリックリンクを作成する
function main () {

  local DOTLIST=(".vimrc" ".bash_profile" ".zprofile" ".zshrc")
  DOTLIST+=(".bashrc")
  DOTLIST+=(".tmux.conf")

  for var in ${DOTLIST[@]}
  do
    create_ln ${var}
  done

  # vim --------------------------------------
  # TODO: 削除
  # vim_setting

  # Neovim -----------------------------------
  neovim_setting

  # fish -------------------------------------
  # TODO: 削除
  # if type fish > /dev/null 2>&1; then
  #   fish_setting
  # fi
}

# vimの設定を行う関数
function vim_setting () {
  log "vimの設定反映"

  # vimの設定ディレクトリが存在しない場合は作成する
  local VIM_DIRS=(".vim" ".vim/colors" ".vim/autoload")
  for var in ${VIM_DIRS[@]}
  do
    set_dir ${var}
  done

  # シンボリックリンクを作成
  local VIM_FILES=(".vim/colors/*.vim" ".vim/autoload/plug.vim")
  for var in ${VIM_FILES[@]}
  do
    create_ln ${var}
  done
}

# シンボリックリンクを貼る関数
# 同じファイルが存在する場合、上書きする
# $1: 対象ファイル
function create_ln () {
  local FILE=$1

  ln -vsf ${DOTPATH}/${FILE} ${HOME}/${FILE}
  return 0
}

# 対象のディレクトリがない場合は作成する関数
# $1: 対象ディレクトリ
function set_dir () {
  local DIR=$1

  if [ ! -d ${HOME}/${DIR} ]; then
    mkdir ${HOME}/${DIR}
  fi
  return 0
}

# main関数実行
main


exit 0
